theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "main"
    path: "/"
  repository_url: "https://github.com/BrandonKowalski/retroid-pocket-classic-compendium"

name: Retroid Pocket Classic Compendium
description: "A distilled, opinionated look at the RPC."
